# Generated by Django 4.0.4 on 2022-05-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamregistered',
            name='PROFILE_PIC_PATH',
            field=models.TextField(blank=True, db_column='PROFILE_PIC_PATH', null=True),
        ),
    ]
