# Generated by Django 4.0.4 on 2022-05-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_dashboard', '0002_alter_teamregistered_profile_pic_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamregistered',
            name='LICENSE_KEY',
            field=models.TextField(blank=True, db_column='LICENSE_KEY', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teamregistered',
            name='IDENTITY_NUM',
            field=models.CharField(db_column='IDENTITY_NUM', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='teamregistered',
            name='POSITION',
            field=models.CharField(blank=True, db_column='POSITION', max_length=20, null=True),
        ),
    ]
