# Generated by Django 4.0.4 on 2022-05-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_dashboard', '0003_teamregistered_license_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamregistered',
            name='REGISTERED_BY',
            field=models.UUIDField(blank=True, db_column='REGISTERED_BY', null=True, unique=True),
        ),
    ]
