# Generated by Django 4.0.4 on 2022-05-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTeams',
            fields=[
                ('PID', models.AutoField(db_column='PID', primary_key=True, serialize=False)),
                ('TEAM_ID', models.UUIDField(db_column='TEAM_ID')),
                ('TEAM', models.CharField(db_column='TEAM', max_length=100)),
                ('LOGO_PATH', models.ImageField(blank=True, db_column='LOGO_PATH', upload_to='')),
                ('SECRET_KEY', models.UUIDField(db_column='SECRET_KEY')),
                ('IS_REGISTERED', models.BooleanField(db_column='IS_REGISTERED', default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AvailableTournaments',
            fields=[
                ('PID', models.AutoField(db_column='PID', primary_key=True, serialize=False)),
                ('TOURNAMENT_ID', models.UUIDField(db_column='TOURNAMENT_ID')),
                ('TOURNAMENT_TITLE', models.CharField(db_column='TOURNAMENT_TITLE', max_length=255)),
                ('START_TIME', models.DateField(db_column='START_TIME')),
                ('END_TIME', models.DateField(db_column='END_TIME')),
                ('POSTER_PATH', models.ImageField(blank=True, db_column='POSTER_PATH', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MatchDelegatesList',
            fields=[
                ('PID', models.AutoField(db_column='PID', primary_key=True, serialize=False)),
                ('NAME', models.CharField(db_column='NAME', max_length=100)),
                ('DESIGNATION', models.CharField(db_column='DESIGNATION', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MatchInformations',
            fields=[
                ('PID', models.AutoField(db_column='PID', primary_key=True, serialize=False)),
                ('MATCH_ID', models.UUIDField(db_column='MATCH_ID')),
                ('MATCH_NUM', models.IntegerField(db_column='MATCH_NUM', default=0)),
                ('START_TIME', models.DateTimeField(blank=True, db_column='START_TIME')),
                ('END_TIME', models.DateTimeField(blank=True, db_column='END_TIME')),
                ('MATCH_VENUE', models.CharField(blank=True, db_column='MATCH_VENUE', max_length=255)),
                ('TEMPERATURE', models.FloatField(blank=True, db_column='TEMPERATURE')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMatchGeneralInformation',
            fields=[
                ('PID', models.AutoField(db_column='PID', primary_key=True, serialize=False)),
                ('IS_AWAY', models.BooleanField(db_column='IS_AWAY', default=False)),
                ('JERSEY_COLOR', models.JSONField(db_column='JERSEY_COLOR', default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMatchOfficialList',
            fields=[
                ('PID', models.AutoField(db_column='PID', primary_key=True, serialize=False)),
                ('ATTENDANCE', models.BooleanField(db_column='ATTENDANCE', default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMatchPlayerList',
            fields=[
                ('PID', models.AutoField(db_column='PID', primary_key=True, serialize=False)),
                ('ATTENDANCE', models.BooleanField(db_column='ATTENDANCE', default=False)),
                ('IS_FIRST_ELEVEN', models.BooleanField(db_column='IS_FIRST_ELEVEN', default=False)),
                ('IS_SUBSTITUTE', models.BooleanField(db_column='IS_SUBSTITUTE', default=True)),
                ('SCORE_COUNT', models.IntegerField(blank=True, db_column='SCORE_COUNT', default=0)),
                ('PENALTY_CARDS', models.JSONField(db_column='PENALTY_CARDS', default=dict)),
                ('IS_CAPTAIN', models.BooleanField(db_column='IS_CAPTAIN', default=False)),
            ],
        ),
    ]
