# Generated by Django 4.0.4 on 2022-05-06 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_dashboard', '0001_initial'),
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammatchplayerlist',
            name='IDENTITY_NUM',
            field=models.ForeignKey(db_column='IDENTITY_NUM', on_delete=django.db.models.deletion.CASCADE, to='client_dashboard.teamregistered'),
        ),
        migrations.AddField(
            model_name='teammatchplayerlist',
            name='MATCH_ID',
            field=models.ForeignKey(db_column='MATCH_ID', on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.matchinformations'),
        ),
        migrations.AddField(
            model_name='teammatchplayerlist',
            name='TEAM_ID',
            field=models.ForeignKey(db_column='TEAM_ID', on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.availableteams'),
        ),
        migrations.AddField(
            model_name='teammatchofficiallist',
            name='IDENTITY_NUM',
            field=models.ForeignKey(db_column='IDENTITY_NUM', on_delete=django.db.models.deletion.CASCADE, to='client_dashboard.teamregistered'),
        ),
        migrations.AddField(
            model_name='teammatchofficiallist',
            name='MATCH_ID',
            field=models.ForeignKey(db_column='MATCH_ID', on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.matchinformations'),
        ),
        migrations.AddField(
            model_name='teammatchofficiallist',
            name='TEAM_ID',
            field=models.ForeignKey(db_column='TEAM_ID', on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.availableteams'),
        ),
        migrations.AddField(
            model_name='teammatchgeneralinformation',
            name='MATCH_ID',
            field=models.ForeignKey(db_column='MATCH_ID', on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.matchinformations'),
        ),
        migrations.AddField(
            model_name='teammatchgeneralinformation',
            name='TEAM_ID',
            field=models.ForeignKey(db_column='TEAM_ID', on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.availableteams'),
        ),
        migrations.AddField(
            model_name='matchinformations',
            name='TOURNAMENT_ID',
            field=models.ForeignKey(db_column='TOURNAMENT_ID', on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.availabletournaments'),
        ),
        migrations.AddField(
            model_name='matchdelegateslist',
            name='MATCH_ID',
            field=models.ForeignKey(db_column='MATCH_ID', on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.matchinformations'),
        ),
    ]
