# Generated by Django 4.0.4 on 2022-05-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableteams',
            name='LOGO_PATH',
            field=models.TextField(blank=True, db_column='LOGO_PATH', null=True),
        ),
        migrations.AlterField(
            model_name='availabletournaments',
            name='POSTER_PATH',
            field=models.TextField(blank=True, db_column='POSTER_PATH', null=True),
        ),
    ]
