# Generated by Django 4.0.4 on 2022-05-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_alter_availableteams_secret_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletournaments',
            name='END_TIME',
            field=models.DateField(blank=True, db_column='END_TIME', null=True),
        ),
        migrations.AlterField(
            model_name='availabletournaments',
            name='START_TIME',
            field=models.DateField(blank=True, db_column='START_TIME', null=True),
        ),
    ]
