# Generated by Django 4.0.4 on 2022-05-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_alter_availabletournaments_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchinformations',
            name='END_TIME',
        ),
        migrations.RemoveField(
            model_name='matchinformations',
            name='START_TIME',
        ),
        migrations.AddField(
            model_name='matchinformations',
            name='DATE_TIME',
            field=models.DateTimeField(blank=True, db_column='DATE_TIME', null=True),
        ),
    ]
