# Generated by Django 4.0.4 on 2022-05-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_remove_matchinformations_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammatchplayerlist',
            name='IS_ELIGIBLE',
            field=models.BooleanField(db_column='IS_ELIGIBLE', default=False),
        ),
        migrations.AddField(
            model_name='teammatchplayerlist',
            name='IS_PLAYING',
            field=models.BooleanField(db_column='IS_PLAYING', default=False),
        ),
    ]
