# Generated by Django 4.0.4 on 2022-05-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0010_teammatchplayerlist_subs_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchinformations',
            name='ATTENDANCE',
            field=models.IntegerField(blank=True, db_column='ATTENDANCE', default=0, null=True),
        ),
        migrations.AddField(
            model_name='matchinformations',
            name='DURATION',
            field=models.IntegerField(blank=True, db_column='DURATION', default=0, null=True),
        ),
    ]
